import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import test from 'node:test';

import {
  ESTIMATOR,
  ROUNDING,
  estimateCeilingSeconds,
  probeDuration,
} from '../src/proxy/service/audioDuration/index.js';

// Generated byte-for-byte from the published multipart-audio-duration/v1
// fixture definitions. Keeping the generators here makes the shared contract
// reviewable without a runtime, package, or sibling-repository dependency.
const conformanceFixtures = [
  { file: 'wav-16k-mono-3s.wav', format: 'wav', ceiling: 3, hash: 'd303811b8c84619667cd0501342f84ec6cbe69f7aa3856dcf52fabda374c92b8', bytes: wav(16_000, 1, 16, 48_000) },
  { file: 'wav-16k-mono-0.4s.wav', format: 'wav', ceiling: 1, hash: '7e28a155ec8ae58f8483a9f7dc8d8190173ded11c01b5f31e1c6f8ee629916c6', bytes: wav(16_000, 1, 16, 6_400) },
  { file: 'wav-44k-stereo-1.5s.wav', format: 'wav', ceiling: 2, hash: 'fecfb253907d62891cd364bbdf0e2cf291129d492617034240850b1dbf057741', bytes: wav(44_100, 2, 16, 66_150) },
  { file: 'flac-44k-7s.flac', format: 'flac', ceiling: 7, hash: '5ce0e5dd10910df0cb2fde6fb8a25b3f954b56457b5d609beb3ab95f51dff90e', bytes: flac(44_100, 44_100n * 7n) },
  { file: 'mp4-12.5s.m4a', format: 'mp4', ceiling: 13, hash: '6dc1ede550d830fe0674d0a83aa6fa6186e7165a7c55b67751ea804fed5936c5', bytes: mp4(1_000, 12_500) },
  { file: 'webm-9.5s.webm', format: 'webm', ceiling: 10, hash: '65f5d031e8078f750b76ad9c9d7ecb33594e50b82daf44797dda3e0fb3cc31bc', bytes: webm(1_000_000n, 9_500) },
  { file: 'mp3-xing-4s.mp3', format: 'mp3', ceiling: 4, hash: 'bd54833ab47305bd2d16dacf46bcd88324cb70b0c6dd4135bb2f08382f990443', bytes: mp3Xing(153) },
] as const;

const refusalFixtures = [
  { file: 'mp3-headerless.mp3', hash: 'd4315816c30dc49ce99615bcd49741a5cc4e4c432fe689a17098b2cb01a86911', bytes: mp3Headerless() },
  { file: 'flac-unknown-length.flac', hash: '9f53063594df844aab75c0cd3334f6d4618e8a2db09e293246909260d7f5ba10', bytes: flac(44_100, 0n) },
  { file: 'mp4-fragmented.m4a', hash: '356919e210c460860115d7b25123e8a61761aaacd2c486bc972951970b877b3e', bytes: mp4(1_000, 0) },
  { file: 'not-audio.bin', hash: 'd675c9cc57d57e72d1d8ee0395eb5a4ccef114a6f201141305d2ffcbc4db4801', bytes: Buffer.from('this is not an audio container at all') },
  { file: 'flac-implausible.flac', hash: '95e2b067dbbadebb1510c148b0375967fedc6f8658fb2981e800e7d1e0048bc9', bytes: flac(44_100, 44_100n * 25n * 3_600n) },
  { file: 'truncated.wav', hash: '3eb6a75185c8f3d73b3649616ac9ce5aa8c592db724a4f39ffc9c86aa20d2c11', bytes: wav(16_000, 1, 16, 48_000).subarray(0, 20) },
] as const;

test('local estimator declares the published contract identity', () => {
  assert.equal(ESTIMATOR, 'multipart-audio-duration/v1');
  assert.equal(ROUNDING, 'ceil-to-whole-seconds');
  assert.equal(conformanceFixtures.length + refusalFixtures.length, 13);
});

for (const fixture of conformanceFixtures) {
  test(`shared conformance vector accepts ${fixture.file}`, () => {
    assert.equal(sha256(fixture.bytes), fixture.hash);
    const result = probeDuration(fixture.bytes);
    assert.equal(result.format, fixture.format);
    assert.equal(result.exact, true);
    assert.equal(estimateCeilingSeconds(fixture.bytes), fixture.ceiling);
  });
}

for (const fixture of refusalFixtures) {
  test(`shared conformance vector refuses ${fixture.file}`, () => {
    assert.equal(sha256(fixture.bytes), fixture.hash);
    assert.throws(() => estimateCeilingSeconds(fixture.bytes));
  });
}

test('headerless MP3 is detected as inexact rather than accepted as a ceiling', () => {
  assert.equal(probeDuration(mp3Headerless()).exact, false);
});

test('Ogg/Opus remains covered beyond the current shared fixture set', () => {
  const bytes = Buffer.alloc(36);
  bytes.write('OggS', 0, 'ascii');
  bytes.writeBigUInt64LE(48_000n, 6);
  bytes[26] = 1;
  bytes[27] = 8;
  bytes.write('OpusHead', 28, 'ascii');
  assert.equal(estimateCeilingSeconds(bytes), 1);
});

function wav(sampleRate: number, channels: number, bits: number, frames: number): Buffer {
  const blockAlign = channels * bits / 8;
  const byteRate = sampleRate * blockAlign;
  const dataSize = frames * blockAlign;
  const out = Buffer.alloc(44 + dataSize);
  out.write('RIFF', 0, 'ascii');
  out.writeUInt32LE(36 + dataSize, 4);
  out.write('WAVEfmt ', 8, 'ascii');
  out.writeUInt32LE(16, 16);
  out.writeUInt16LE(1, 20);
  out.writeUInt16LE(channels, 22);
  out.writeUInt32LE(sampleRate, 24);
  out.writeUInt32LE(byteRate, 28);
  out.writeUInt16LE(blockAlign, 32);
  out.writeUInt16LE(bits, 34);
  out.write('data', 36, 'ascii');
  out.writeUInt32LE(dataSize, 40);
  return out;
}

function flac(sampleRate: number, totalSamples: bigint): Buffer {
  const out = Buffer.alloc(42);
  out.write('fLaC', 0, 'ascii');
  out[4] = 0;
  out.set([0, 0, 34], 5);
  const packed = (BigInt(sampleRate) << 44n) | (15n << 36n) | totalSamples;
  out.writeBigUInt64BE(packed, 18);
  return out;
}

function mp4(timescale: number, duration: number): Buffer {
  const mvhd = Buffer.alloc(20);
  mvhd.writeUInt32BE(timescale, 12);
  mvhd.writeUInt32BE(duration, 16);
  return Buffer.concat([
    box('ftyp', Buffer.from('M4A isom', 'ascii')),
    box('moov', box('mvhd', mvhd)),
  ]);
}

function box(type: string, payload: Buffer): Buffer {
  const out = Buffer.alloc(8 + payload.length);
  out.writeUInt32BE(out.length, 0);
  out.write(type, 4, 'ascii');
  payload.copy(out, 8);
  return out;
}

function webm(timecodeScaleNs: bigint, durationTicks: number): Buffer {
  const scale = Buffer.alloc(8);
  scale.writeBigUInt64BE(timecodeScaleNs);
  const duration = Buffer.alloc(8);
  duration.writeDoubleBE(durationTicks);
  const info = Buffer.concat([
    Buffer.from([0x2a, 0xd7, 0xb1, 0x88]),
    scale,
    Buffer.from([0x44, 0x89, 0x88]),
    duration,
  ]);
  return Buffer.concat([
    Buffer.from([0x1a, 0x45, 0xdf, 0xa3, 0x84, 0, 0, 0, 0]),
    ebmlElement(
      Buffer.from([0x18, 0x53, 0x80, 0x67]),
      ebmlElement(Buffer.from([0x15, 0x49, 0xa9, 0x66]), info),
    ),
  ]);
}

function ebmlElement(id: Buffer, payload: Buffer): Buffer {
  const size = Buffer.alloc(8);
  size.writeBigUInt64BE(BigInt(payload.length));
  size[0] = 0x01;
  return Buffer.concat([id, size, payload]);
}

function mp3Frame(): Buffer {
  return Buffer.from([0xff, 0xfb, 0x90, 0x00]);
}

function mp3Xing(frames: number): Buffer {
  const out = Buffer.alloc(112);
  mp3Frame().copy(out);
  out.write('Xing', 36, 'ascii');
  out.writeUInt32BE(1, 40);
  out.writeUInt32BE(frames, 44);
  return out;
}

function mp3Headerless(): Buffer {
  const frame = Buffer.alloc(417);
  mp3Frame().copy(frame);
  return Buffer.concat(Array.from({ length: 40 }, () => frame));
}

function sha256(bytes: Uint8Array): string {
  return createHash('sha256').update(bytes).digest('hex');
}
